#ifndef ASEMBLER_ERRORS_H
#define ASEMBLER_ERRORS_H

typedef enum {
    INPUT_EXCEEDS_MAX_LEN,
    UNDEFINED_CMD,
    VALUE_OUT_OF_RANGE,
    REG_OUT_OF_BOUNDS,
    NOT_AN_INT,
    NOT_A_REG,
    REG_MUST_START_WITH,
    MISSING_PARAM,
    EXTRANEOUS_TEXT,
    MULTIPLE_CONSECUTIVE_COMMAS,
    MISSING_COMMA,
    ILLEGAL_COMMA,
    STR_MUST_BE_ASCII,
    STR_MUST_TERMINATE_WITH_DQ,
    STR_MUST_START_WITH_DQ,
    ILLEGAL_SPACE_BETWEEN_REG_AND_NUM,
    ILLEGAL_SPACE_BETWEEN_DOT,
    ILLEGAL_SPACE_BEFORE_COLON,
    NOT_A_LABEL,
    LABEL_MUST_START_WITH_ALPHA,
    LABEL_ALLOWED_ONLY_ALPHANUM,
    LABEL_CANNOT_BE_SAVED_WORD,
    LABEL_ALREADY_DEFINED,
    LABEL_TOO_LONG,
    LABEL_NOT_PREV_DEFINED,
    LABEL_ALREADY_EXT,
    LABEL_CANNOT_BE_EXT,
    NO_ERROR,
    END_OF_LINE
} ERROR;

#endif /*ASEMBLER_ERRORS_H*/
